# Derive all application and package versions from the nearest release tag.
# VERSION.txt provides a deterministic baseline for source archives and repositories
# that have not yet created their first semantic-version tag.
file(READ "${CMAKE_CURRENT_LIST_DIR}/../VERSION.txt" PRG32QT_VERSION_BASE)
string(STRIP "${PRG32QT_VERSION_BASE}" PRG32QT_VERSION_BASE)
if(NOT PRG32QT_VERSION_BASE MATCHES "^[0-9]+\.[0-9]+\.[0-9]+$")
  message(FATAL_ERROR "VERSION.txt must contain X.Y.Z")
endif()

set(PRG32QT_VERSION_CORE "${PRG32QT_VERSION_BASE}")
set(PRG32QT_VERSION "${PRG32QT_VERSION_BASE}")
set(PRG32QT_VERSION_DISTANCE 0)
set(PRG32QT_VERSION_HASH "archive")
set(PRG32QT_VERSION_RELEASE OFF)

find_package(Git QUIET)
if(Git_FOUND AND EXISTS "${CMAKE_CURRENT_LIST_DIR}/../.git")
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" describe --tags --match "v[0-9]*.[0-9]*.[0-9]*" --long --always
    WORKING_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}/.."
    OUTPUT_VARIABLE PRG32QT_GIT_DESCRIBE_RESULT
    OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE PRG32QT_GIT_DESCRIBE_STATUS
    ERROR_QUIET)
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" rev-parse --short=12 HEAD
    WORKING_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}/.."
    OUTPUT_VARIABLE PRG32QT_GIT_HASH_RESULT
    OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE PRG32QT_GIT_HASH_STATUS
    ERROR_QUIET)
  if(PRG32QT_GIT_HASH_STATUS EQUAL 0 AND PRG32QT_GIT_HASH_RESULT MATCHES "^[0-9a-f]+$")
    set(PRG32QT_VERSION_HASH "${PRG32QT_GIT_HASH_RESULT}")
  endif()
  if(PRG32QT_GIT_DESCRIBE_STATUS EQUAL 0 AND PRG32QT_GIT_DESCRIBE_RESULT MATCHES "^v([0-9]+\.[0-9]+\.[0-9]+)-([0-9]+)-g([0-9a-f]+)$")
    set(PRG32QT_VERSION_TAG "${CMAKE_MATCH_1}")
    set(PRG32QT_VERSION_DISTANCE "${CMAKE_MATCH_2}")
    set(PRG32QT_VERSION_HASH "${CMAKE_MATCH_3}")
    if(PRG32QT_VERSION_DISTANCE EQUAL 0)
      if(NOT PRG32QT_VERSION_BASE VERSION_EQUAL PRG32QT_VERSION_TAG)
        message(FATAL_ERROR "VERSION.txt ${PRG32QT_VERSION_BASE} must match release tag v${PRG32QT_VERSION_TAG}")
      endif()
      set(PRG32QT_VERSION_CORE "${PRG32QT_VERSION_TAG}")
      set(PRG32QT_VERSION "${PRG32QT_VERSION_CORE}")
      set(PRG32QT_VERSION_RELEASE ON)
    else()
      if(PRG32QT_VERSION_BASE VERSION_LESS PRG32QT_VERSION_TAG)
        message(FATAL_ERROR "VERSION.txt ${PRG32QT_VERSION_BASE} is older than v${PRG32QT_VERSION_TAG}")
      endif()
      set(PRG32QT_VERSION "${PRG32QT_VERSION_CORE}-dev.${PRG32QT_VERSION_DISTANCE}+g${PRG32QT_VERSION_HASH}")
    endif()
  else()
    execute_process(
      COMMAND "${GIT_EXECUTABLE}" rev-list --count HEAD
      WORKING_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}/.."
      OUTPUT_VARIABLE PRG32QT_GIT_COUNT_RESULT
      OUTPUT_STRIP_TRAILING_WHITESPACE
      RESULT_VARIABLE PRG32QT_GIT_COUNT_STATUS
      ERROR_QUIET)
    if(PRG32QT_GIT_COUNT_STATUS EQUAL 0 AND PRG32QT_GIT_COUNT_RESULT MATCHES "^[0-9]+$")
      set(PRG32QT_VERSION_DISTANCE "${PRG32QT_GIT_COUNT_RESULT}")
    endif()
    set(PRG32QT_VERSION "${PRG32QT_VERSION_BASE}-dev.${PRG32QT_VERSION_DISTANCE}+g${PRG32QT_VERSION_HASH}")
  endif()
endif()

string(REPLACE "." ";" PRG32QT_VERSION_PARTS "${PRG32QT_VERSION_CORE}")
list(GET PRG32QT_VERSION_PARTS 0 PRG32QT_VERSION_MAJOR)
list(GET PRG32QT_VERSION_PARTS 1 PRG32QT_VERSION_MINOR)
list(GET PRG32QT_VERSION_PARTS 2 PRG32QT_VERSION_PATCH)
math(EXPR PRG32QT_ANDROID_VERSION_CODE
  "${PRG32QT_VERSION_MAJOR} * 100000000 + ${PRG32QT_VERSION_MINOR} * 1000000 + ${PRG32QT_VERSION_PATCH} * 10000")
if(PRG32QT_VERSION_RELEASE)
  math(EXPR PRG32QT_ANDROID_VERSION_CODE "${PRG32QT_ANDROID_VERSION_CODE} + 9999")
else()
  math(EXPR PRG32QT_VERSION_BUILD "${PRG32QT_VERSION_DISTANCE} % 9999")
  math(EXPR PRG32QT_ANDROID_VERSION_CODE "${PRG32QT_ANDROID_VERSION_CODE} + ${PRG32QT_VERSION_BUILD}")
endif()
if(PRG32QT_ANDROID_VERSION_CODE LESS 1)
  set(PRG32QT_ANDROID_VERSION_CODE 1)
endif()

message(STATUS "PRG32-QT version: ${PRG32QT_VERSION}")
